# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "60...100"
  
  status:
    project:
      default:
        target: auto
        threshold: 5%  # Allow 5% coverage drop
        informational: true  # Don't fail CI on coverage drop initially
    patch:
      default:
        target: 80%
        informational: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/**/*"
  - "temp/**/*"
  - "example/**/*"
  - "**/__pycache__/**"

