"""
Weights & Biases logging utility.

Provides a thin WandbRun wrapper that:
- Reads logger config from cfg.logger (populated by configs/logger/*.yaml)
- Degrades gracefully to a no-op when logger.enabled=False or wandb is absent
- Supports online / offline / disabled modes for local, host, and HPC use

Typical usage
-------------
    from pmf_tsfm.utils.wandb_logger import WandbRun, init_run

    run = init_run(cfg, job_type="inference", name="chronos2/BPI2017")
    run.log({"train/loss": 0.42}, step=1)
    run.log_summary({"mae_mean": 1.23, "elapsed_s": 42.0})
    run.finish()

Enabling W&B
------------
    # Online (default for host/laptop)
    python -m pmf_tsfm.inference logger=wandb

    # Offline (HPC nodes without internet; sync later with `wandb sync`)
    python -m pmf_tsfm.inference logger=wandb_offline

    # Machine-specific default in configs/local/default.yaml (git-ignored):
    #   logger:
    #     entity: your-wandb-username
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from omegaconf import DictConfig


class WandbRun:
    """
    A W&B run wrapper that silently ignores all calls when disabled.

    Construct via init_run(); do not instantiate directly.
    """

    def __init__(self, run: Any) -> None:
        self._run = run

    @property
    def enabled(self) -> bool:
        return self._run is not None

    def log(self, metrics: dict[str, Any], step: int | None = None) -> None:
        """Log a dict of metrics, optionally at a given step."""
        if self._run is not None:
            if step is not None:
                self._run.log(metrics, step=step)
            else:
                self._run.log(metrics)

    def log_summary(self, summary: dict[str, Any]) -> None:
        """Write key-value pairs to the run summary (single values, not time-series)."""
        if self._run is not None:
            for k, v in summary.items():
                self._run.summary[k] = v

    def log_table(self, key: str, columns: list[str], rows: list[list[Any]]) -> None:
        """Log a W&B Table artifact (useful for per-model comparison tables)."""
        if self._run is not None:
            try:
                import wandb

                table = wandb.Table(columns=columns, data=rows)
                self._run.log({key: table})
            except ImportError:
                pass

    def finish(self) -> None:
        """Mark the run as finished and flush remaining data."""
        if self._run is not None:
            self._run.finish()


def init_run(
    cfg: DictConfig,
    *,
    job_type: str,
    name: str | None = None,
    tags: list[str] | None = None,
    group: str | None = None,
) -> WandbRun:
    """
    Initialise a W&B run from the Hydra config.

    Reads ``cfg.logger`` (set via ``logger=wandb`` / ``logger=wandb_offline``).
    Returns a no-op WandbRun when logging is disabled or wandb is not installed.

    Args:
        cfg:      Full resolved Hydra DictConfig.
        job_type: Pipeline stage label shown in W&B UI
                  (e.g. ``"inference"``, ``"train"``, ``"evaluate"``, ``"er"``).
        name:     Human-readable run name (auto-generated by W&B if None).
        tags:     Extra tags appended to those in cfg.logger.tags.
        group:    Run group (overrides cfg.logger.group when set).

    Returns:
        WandbRun — real or no-op depending on configuration.
    """
    logger_cfg = cfg.get("logger", None)
    if logger_cfg is None or not logger_cfg.get("enabled", False):
        return WandbRun(None)

    try:
        import wandb
    except ImportError:
        print("Warning: wandb not installed. Run: uv add wandb")
        return WandbRun(None)

    from omegaconf import OmegaConf

    all_tags: list[str] = list(logger_cfg.get("tags") or [])
    if tags:
        all_tags.extend(tags)

    resolved_group: str | None = group or logger_cfg.get("group") or None
    entity: str | None = logger_cfg.get("entity") or None

    config_dict = OmegaConf.to_container(cfg, resolve=True, throw_on_missing=False)

    run = wandb.init(
        project=logger_cfg.get("project", "pmf-tsfm"),
        entity=entity,
        mode=logger_cfg.get("mode", "online"),
        job_type=job_type,
        name=name,
        tags=all_tags or None,
        group=resolved_group,
        notes=logger_cfg.get("notes") or None,
        config=config_dict,
        reinit=True,
    )
    return WandbRun(run)
