#!/usr/bin/env bash
# =============================================================================
# setup_vsc.sh — One-time environment setup on VSC.
#
# Run this ONCE from a login node (not a compute node) before submitting jobs:
#   bash scripts/hpc/setup_vsc.sh
#
# What it does:
#   1. Installs uv to VSC_DATA (survives scratch cleanup)
#   2. Clones / pulls the repo to VSC_SCRATCH
#   3. Installs Python dependencies via uv sync
#   4. Pre-downloads model checkpoints to VSC_SCRATCH cache
#   5. Syncs processed data from VSC_DATA to VSC_SCRATCH
#   6. Writes .env for the project
#
# Re-run anytime to refresh the repo or re-download checkpoints.
# =============================================================================
set -euo pipefail
source "$(dirname "$0")/hpc_env.sh"

GITHUB_REPO="https://github.com/YongboYu/pmf-tsfm.git"
GITHUB_BRANCH="main"

echo "================================================================"
echo "  PMF-TSFM VSC Setup"
echo "  DATA:    ${VSC_DATA}"
echo "  SCRATCH: ${VSC_SCRATCH}"
echo "================================================================"

# ── Step 1: Install uv ───────────────────────────────────────────────────────
echo ""
echo "[1/6] Installing uv..."
mkdir -p "${VSC_DATA}/.local/bin"
if [[ ! -x "${UV}" ]]; then
    curl -LsSf https://astral.sh/uv/install.sh | \
        INSTALLER_NO_MODIFY_PATH=1 UV_INSTALL_DIR="${VSC_DATA}/.local/bin" sh
    echo "  uv installed at ${UV}"
else
    echo "  uv already installed: $(${UV} --version)"
fi

# ── Step 2: Clone / pull repo to SCRATCH ────────────────────────────────────
echo ""
echo "[2/6] Setting up repo at ${PROJECT_ROOT}..."
_ensure_scratch_dirs
if [[ -d "${PROJECT_ROOT}/.git" ]]; then
    echo "  Pulling latest changes..."
    git -C "${PROJECT_ROOT}" fetch origin
    git -C "${PROJECT_ROOT}" checkout "${GITHUB_BRANCH}"
    git -C "${PROJECT_ROOT}" pull origin "${GITHUB_BRANCH}"
else
    echo "  Cloning ${GITHUB_REPO}..."
    git clone --branch "${GITHUB_BRANCH}" "${GITHUB_REPO}" "${PROJECT_ROOT}"
fi
echo "  Repo at: $(git -C "${PROJECT_ROOT}" log --oneline -1)"

# ── Step 3: Install Python dependencies ─────────────────────────────────────
echo ""
echo "[3/6] Installing dependencies via uv sync..."
_load_modules
(
    cd "${PROJECT_ROOT}"
    # Core dependencies
    "${UV}" sync --frozen
    # TimesFM legacy extras (for 1.0 and 2.0 models)
    "${UV}" sync --frozen --extra timesfm_legacy
    # TimesFM 2.5 extras
    "${UV}" sync --frozen --extra timesfm_v25
)
echo "  Dependencies installed."

# ── Step 4: Write .env for the project ──────────────────────────────────────
echo ""
echo "[4/6] Writing .env..."
ENV_FILE="${PROJECT_ROOT}/.env"
cat > "${ENV_FILE}" << EOF
# Auto-generated by setup_vsc.sh — do not commit
PROJECT_ROOT=${PROJECT_ROOT}
WANDB_API_KEY=${WANDB_API_KEY:-}
WANDB_PROJECT=${WANDB_PROJECT}
WANDB_ENTITY=${WANDB_ENTITY}
TIMESFM_V1_PATH=${TIMESFM_V1_PATH}
TOKENIZERS_PARALLELISM=false
HF_HOME=${HF_HOME}
TORCH_HOME=${TORCH_HOME}
EOF
echo "  Written to ${ENV_FILE}"

# ── Step 5: Sync processed data from DATA → SCRATCH ─────────────────────────
echo ""
echo "[5/6] Syncing processed data from VSC_DATA to VSC_SCRATCH..."
if [[ -d "${DATA_ROOT}/data" ]]; then
    rsync -av --progress "${DATA_ROOT}/data/" "${DATA_DIR}/"
    echo "  Data ready at ${DATA_DIR}"
else
    echo "  WARNING: ${DATA_ROOT}/data not found."
    echo "  Upload your processed data to VSC_DATA first:"
    echo "    rsync -av data/ ${VSC_DATA}/${PROJECT_NAME}/data/"
fi

# ── Step 6: Pre-download model checkpoints to SCRATCH cache ─────────────────
echo ""
echo "[6/6] Pre-downloading model checkpoints to SCRATCH cache..."
echo "  HF_HOME = ${HF_HOME}"
echo ""
echo "  Downloading Chronos models..."
(
    cd "${PROJECT_ROOT}"
    "${UV}" run --no-sync python - << 'PYEOF'
from huggingface_hub import snapshot_download
import os

models = [
    "amazon/chronos-bolt-tiny",
    "amazon/chronos-bolt-mini",
    "amazon/chronos-bolt-small",
    "amazon/chronos-bolt-base",
    "amazon/chronos-t5-tiny",
    "amazon/chronos-t5-mini",
    "amazon/chronos-t5-small",
    "amazon/chronos-t5-base",
    "amazon/chronos-t5-large",
]
for model_id in models:
    print(f"  {model_id}...", flush=True)
    try:
        snapshot_download(model_id)
        print(f"    OK")
    except Exception as e:
        print(f"    FAILED: {e}")
PYEOF
)

echo ""
echo "  Downloading Chronos-2..."
(
    cd "${PROJECT_ROOT}"
    "${UV}" run --no-sync python - << 'PYEOF'
from huggingface_hub import snapshot_download
print("  amazon/chronos-2-base...", flush=True)
try:
    snapshot_download("amazon/chronos-2-base")
    print("    OK")
except Exception as e:
    print(f"    FAILED: {e}")
PYEOF
)

echo ""
echo "  Downloading MOIRAI models..."
(
    cd "${PROJECT_ROOT}"
    "${UV}" run --no-sync python - << 'PYEOF'
from huggingface_hub import snapshot_download

models = [
    "Salesforce/moirai-1.1-R-small",
    "Salesforce/moirai-1.1-R-base",
    "Salesforce/moirai-1.1-R-large",
    "Salesforce/moirai-moe-base",
    "Salesforce/moirai-2.0-R-small",
]
for model_id in models:
    print(f"  {model_id}...", flush=True)
    try:
        snapshot_download(model_id)
        print(f"    OK")
    except Exception as e:
        print(f"    FAILED: {e}")
PYEOF
)

echo ""
echo "  Downloading TimesFM 2.5..."
(
    cd "${PROJECT_ROOT}"
    "${UV}" run --no-sync --extra timesfm_v25 python - << 'PYEOF'
from huggingface_hub import snapshot_download
print("  google/timesfm-2.5-200m-pytorch...", flush=True)
try:
    snapshot_download("google/timesfm-2.5-200m-pytorch")
    print("    OK")
except Exception as e:
    print(f"    FAILED: {e}")
PYEOF
)

echo ""
echo "  NOTE: TimesFM 1.0 / 2.0 weights download automatically on first run."
echo "  Ensure TIMESFM_V1_PATH=${TIMESFM_V1_PATH} points to v1.2.6 source."
if [[ ! -d "${TIMESFM_V1_PATH}" ]]; then
    echo ""
    echo "  ACTION REQUIRED: Clone TimesFM v1.2.6 to VSC_DATA:"
    echo "    git clone --depth 1 --branch v1.2.6 \\"
    echo "        https://github.com/google-research/timesfm.git \\"
    echo "        \${VSC_DATA}/timesfm-v1-repo"
fi

echo ""
echo "================================================================"
echo "  Setup complete."
echo "  Next steps:"
echo "    1. Set WANDB_API_KEY in ${ENV_FILE}"
echo "    2. Submit jobs: bash scripts/hpc/submit_pipeline.sh"
echo "================================================================"
